#!/usr/bin/bash

read -p "Do you want to install PARU the better AUR Helper? [Y/n] " yn
case $yn in
[Yy]*)
    git clone https://aur.archlinux.org/paru.git $HOME/.paru
    cd $HOME/.paru
    makepkg -si --noconfirm
    ;;
[Nn]*) ;;
"")
    git clone https://aur.archlinux.org/paru.git $HOME/.paru
    cd $HOME/.paru
    makepkg -si --noconfirm
    ;;
*) echo "Please answer y/n TRY AGAIN!" ;;
esac

read -p "Do you want to install NEOVIM? [Y/n] " yn
case $yn in
[Yy]*)
    sudo pacman -S neovim nodejs python-pip
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
    yarn global add neovim
    paru -S npm neovim-colorbuddy-git instant-markdown-d nvim-packer-git
    sudo npm i -g typescript typescript-language-server
    python3 -m pip install --user --upgrade pynvim
    cd
    ;;
[Nn]*) ;;
"")
    sudo pacman -S neovim nodejs python-pip
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
    yarn global add neovim
    paru -S npm neovim-colorbuddy-git instant-markdown-d nvim-packer-git
    sudo npm i -g typescript typescript-language-server
    python3 -m pip install --user --upgrade pynvim
    cd
    ;;
*) echo "Please answer y/n TRY AGAIN!" ;;
esac

printf "\e[1;32m#########################################\e[0m\n"
printf "\e[1;32m## Installing GTK, ICONS, CURSOR, ETC. ##\e[0m\n"
printf "\e[1;32m#########################################\e[0m\n"

paru -S python-iwlib sardi-icons
paru -S --aur preload picom-git light-git devour simple-mtpfs networkmanager-dmenu-git

printf "\e[1;32m######################\e[0m\n"
printf "\e[1;32m## Installing FONTS ##\e[0m\n"
printf "\e[1;32m######################\e[0m\n"

paru -S ttc-iosevka-aile ttf-cascadia-code ttf-fira-code ttf-fira-mono ttf-font-awesome ttf-inconsolata ttf-jetbrains-mono ttf-ubuntu-font-family ttf-mononoki otf-raleway ttf-ms-fonts noto-color-emoji-fontconfig adobe-source-code-pro-fonts adobe-source-han-sans-cn-fonts ttf-icomoon-feather ttf-ibmplex-mono-nerd

printf "\e[1;32m#############################\e[0m\n"
printf "\e[1;32m## Installing DEVELOPMENTS ##\e[0m\n"
printf "\e[1;32m#############################\e[0m\n"

sudo pacman -S openjdk11-src python-pip cmake python-jedi python-pylint clang
paru -S google-java-format min visual-studio-code-bin

printf "\e[1;32m#############################\e[0m\n"
printf "\e[1;32m## Installing DEPENDENCIES ##\e[0m\n"
printf "\e[1;32m#############################\e[0m\n"

sudo pacman -S tlp tlp-rdw ufw qutebrowser rofi lxappearance udisks2 pcmanfm scrot nitrogen lxsession volumeicon xcb-util-cursor exa sxiv mpv pavucontrol plocate dunst pamixer conky alacritty blueberry trayer fish brightnessctl blueman stow zathura zathura-pdf-poppler vimb gnome-keyring emacs dmenu xdo xdotool fisher ripgrep tmux aria2 gparted network-manager-applet networkmanager polybar prettier python-pywal xclip fd xidlehook
sh -c "$(curl -fsSL https://starship.rs/install.sh)"

pip3 install psutil

# Enable daemon
sudo systemctl enable tlp.service
sudo systemctl enable ufw.service
sudo systemctl enable preload.service
# sudo systemctl enable nvidia-hibernate.service
# sudo systemctl enable nvidia-persistenced.service
# sudo systemctl enable nvidia-resume.service
# sudo systemctl enable nvidia-suspend.service

while true; do
    read -p "Do you want to reboot? (recommended) [Y/n] " yn
    case $yn in
    [Yy]*) reboot ;;
    [Nn]*)
        exit
        break
        ;;
    "") reboot ;;
    *) printf "\e[1;32mPlease answer y or n.\e[0m\n" ;;
    esac
done
