#! /bin/sh

# Start applications from ~/.local/bin/autostart
autostart &

# bspwm settings
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 &
bspc config window_gap 10
bspc config border_width 2
bspc config normal_border_color "#313244"
bspc config focused_border_color "#7f849c"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc rule -a Alacritty state=floating
# bspc rule -a Pcmanfm state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Code desktop='^1'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Pcmanfm desktop='^3'
bspc rule -a Alacritty desktop='^4'
bspc rule -a Spotify desktop='^7'
