#! /bin/sh

# Start applications from ~/.local/bin/autostart
autostart &
redshift-gtk &

# bspwm settings
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 &
bspc config window_gap 4
bspc config border_width 2
bspc config normal_border_color "#313244"
bspc config focused_border_color "#7f849c"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc rule -a Alacritty state=floating
bspc rule -a TelegramDesktop state=floating
bspc rule -a Zathura state=tiling
bspc rule -a firefox desktop='^2'
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a Spotify desktop='^7'
